basePath: /api/v1
info:
  contact:
    email: vvuri1978@gmail.com
    name: API Support
  description: Swagger API for Golang Project Goblog.
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: Goblog Swagger API
  version: "1.0"
paths:
  /ping:
    get:
      responses:
        "200":
          description: ""
      summary: Ping Pong test
  /user/:name:
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
      security:
      - ApiKeyAuth: []
      summary: Retrieves user based on given ID
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
