basePath: /api/v1
info:
  contact:
    email: vvuri1978@gmail.com
    name: API Support
  description: Swagger API for Golang Project Goblog.
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: Goblog Swagger API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
